version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - knockout-network

networks:
  knockout-network:
    external: true